version: '3'

services:
### cache ###
  redis:
    image: redis:${redis_version}
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - default

### queue ###
  rabbitmq:
    image: rabbitmq:${rabbitmq_version}
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

### database ###
  mysql: # root/rootroot
    image: mysql:${mysql_version}
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - default
  oracle: # xe/system/oracle
    image: oracleinanutshell/oracle-xe-11g:${oracle_xe_version}
    expose:
      - 1521
    ports:
      - "1521:1521"
    networks:
      - default
  mongo:
    image: mongo:${mongodb_version}
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot
    networks:
      - default
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootroot
    depends_on:
      - mongo
    networks:
      - default

### Elastic Stack ###
  elastic-kibana:
    image: docker.elastic.co/kibana/kibana:${elastic_kibana_version}
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS="http://elastic-elasticsearch:9200"
    networks:
      - default
    depends_on:
      - elastic-elasticsearch
  elastic-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${elastic_elasticsearch_version}
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - default
  elastic-logstash:
    image: docker.elastic.co/logstash/logstash:${elastic_logstash_version}
    ports:
      - "5000:5000"
      - "12201:12201/udp"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - default
    depends_on:
      - elastic-kibana

networks:
  default:
