version: '3'

services:
### cache ###
  redis:
    image: redis:${redis_version}
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - default

### queue ###
  rabbitmq:
    image: rabbitmq:${rabbitmq_version}
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

### database ###
  mysql: # root/rootroot
    image: mysql:${mysql_version}
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - default
  oracle: # xe/system/oracle
    image: oracleinanutshell/oracle-xe-11g:${oracle_xe_version}
    expose:
      - 1521
    ports:
      - "1521:1521"
    networks:
      - default

networks:
  default:
